theme = "blowfish"
baseURL = "http://localhost:1313/"
title = "Baú de Recursos Escutistas"
languageCode = "pt"
defaultContentLanguage = "pt"
disableLanguages = ["en"]
enableRobotsTXT = true
enableEmoji = true


[params]
description = "Baú de Recursos Escutistas - Iniciativa de formação escutista"
dateFormat = "2 January 2006"

[params.footer]
copyright = "🧦Uma Meia na Tenda ⛺  /2026"

[taxonomies]
tag = "tags"
category = "categories"

[menu]
[[menu.main]]
name = "🎯 Jogos"
pageRef = "games"
weight = 10

[[menu.main]]
name = "📖 Recursos"
pageRef = "library"
weight = 20

[[menu.main]]
name = "🛠️ Ferramentas"
pageRef = "tools"
weight = 30

[[menu.footer]]
name = "📋 Reportar Conteúdo"
url = "https://github.com/rogerio-ar-costa/uma-meia-na-tenda/issues/new"
weight = 10
[menu.footer.params]
newTab = true
